# Generated by Django 3.1.2 on 2020-10-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200424_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_ad',
            options={'verbose_name': 'Коментар AD', 'verbose_name_plural': 'Коментарі AD'},
        ),
        migrations.AlterModelOptions(
            name='comment_pg',
            options={'verbose_name': 'Коментар PG', 'verbose_name_plural': 'Коментарі PG'},
        ),
    ]
